# Generated by Django 4.0.4 on 2022-05-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_course', '0002_tag_course_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='tags',
        ),
        migrations.AddField(
            model_name='lesson',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='api_course.tag'),
        ),
    ]
